### ISSUE TITLE
MAT model not loading

### ISSUE THREAD

**Issue by HettieC** [COBREXA/MATFBCModels.jl#11]
Hello! Realised my COBREXA issue should have been directly here...

I'm trying to load a MAT model, and am getting an ```InexactError: Int64(NaN)``` resulting from some of the metabolite charges in the model being ```NaN```.

The model I am using is the yeast-GEM.mat from [here](https://github.com/SysBioChalmers/yeast-GEM/tree/main/model).

Looks like the util ```parse_charge(x)``` just needs an extra case for ```NaN```.

Thanks!

**Comment by exaexa** [comment]
hello! Just a quick check, are you sure you're on the latest verison? I thought I already fixed this here https://github.com/COBREXA/MATFBCModels.jl/pull/9/files#diff-47c27891e951c8cd946b850dc2df31082624afdf57446c21cb6992f5f4b74aa2R33 which was actually the last time you've reported the yeast gem problems.

If it's still not fixed please let me know.

For the package versions you can do `]status` or possibly `]update` or something

**Comment by HettieC** [comment]
No I forgot to update the version... thanks!!
