### ISSUE TITLE
MAT model not converting to CanonicalModel

### ISSUE THREAD

**Issue by HettieC** [COBREXA/MATFBCModels.jl#8]
Next issue... the yeast-GEM downloaded from [here](https://github.com/SysBioChalmers/yeast-GEM/blob/main/model/yeast-GEM.mat) errors when converted to a `CanonicalModel`

```
using MATFBCModels, COBREXA
import AbstractFBCModels.CanonicalModel as CM
model = convert(CM.Model,load_model("yeast-GEM.mat"))
```

Think it was initially a problem in v1 as well but can't remember what the problem actually was!

**Comment by exaexa** [comment]
@HettieC should be fixed by #9 , I'll try to release that ASAP.
